// src/types/cabinet.ts

// ─── 基礎型別 ─────────────────────────────────────────────────────────────────

export interface AreaMeasure {
  cm2: number;
  m2: number;
  cai: number;
}

export interface MaterialRef {
  materialId: string;
  materialName: string;
  unit: string;
  pricePerUnit: number;
}

// ─── 輸入型別 ─────────────────────────────────────────────────────────────────

export type DoorType = "HINGED" | "SLIDING";

export interface DoorInput {
  id: string;
  type: DoorType;
  name: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  materialRef: MaterialRef | null;
  hingeMaterialRef?: MaterialRef | null;
  railMaterialRef?: MaterialRef | null;
}

export interface MiddleDividerInput {
  id: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  materialRef: MaterialRef | null;
}

export interface ShelfInput {
  id: string;
  widthCm: number;
  depthCm: number;
  quantity: number;
  materialRef: MaterialRef | null;
}

export interface KickPlateInput {
  widthCm: number;
  heightCm: number;
  materialRef: MaterialRef | null;
}

export interface CabinetUnitInput {
  id: string;
  name: string;
  widthCm: number;
  depthCm: number;
  heightCm: number;
  quantity: number;
  hasBackPanel: boolean;
  panelMaterialRef: MaterialRef | null;
  backPanelMaterialRef: MaterialRef | null;
  middleDividers: MiddleDividerInput[];
  shelves: ShelfInput[];
  doors: DoorInput[];
  kickPlate: KickPlateInput | null;
}

// ─── 輸出型別 ─────────────────────────────────────────────────────────────────

export interface PanelResult {
  id: string;
  name: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  singleArea: AreaMeasure;
  totalArea: AreaMeasure;
  materialRef: MaterialRef | null;
  unitCost: number;
  subtotal: number;
  isAutoGenerated: boolean;
}

export interface DoorResult {
  id: string;
  type: DoorType;
  name: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  singleArea: AreaMeasure;
  totalArea: AreaMeasure;
  materialRef: MaterialRef | null;
  subtotal: number;
}

export interface HardwareResult {
  id: string;
  name: string;
  description: string;
  quantity: number;
  materialRef: MaterialRef | null;
  unitCost: number;
  subtotal: number;
}

export interface AccessoryResult {
  id: string;
  name: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  singleArea: AreaMeasure;
  totalArea: AreaMeasure;
  materialRef: MaterialRef | null;
  subtotal: number;
}

export interface CabinetUnitSummary {
  totalAreaCm2: number;
  totalAreaM2: number;
  totalAreaCai: number;
  panelsCost: number;
  internalPartsCost: number;
  doorsCost: number;
  hardwareCost: number;
  accessoriesCost: number;
  totalCost: number;
}

export interface CabinetUnitResult {
  unitId: string;
  unitName: string;
  quantity: number;
  panels: PanelResult[];
  internalParts: PanelResult[];
  doors: DoorResult[];
  hardware: HardwareResult[];
  accessories: AccessoryResult[];
  summary: CabinetUnitSummary;
}

export interface CabinetProjectResult {
  unitResults: CabinetUnitResult[];
  projectTotal: number;
}
