// src/components/cabinet/CabinetResultPanel.tsx
"use client";

import type { CabinetUnitResult } from "@/types";
import { formatCurrency, formatNumber } from "@/lib/utils";
import { AreaDisplay } from "@/components/shared/AreaDisplay";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";

interface Props {
  result: CabinetUnitResult;
}

function PanelTable({ title, rows }: { title: string; rows: CabinetUnitResult["panels"] }) {
  if (rows.length === 0) return null;
  return (
    <div>
      <h4 className="text-sm font-semibold mb-2 text-muted-foreground uppercase tracking-wide">{title}</h4>
      <table className="w-full text-xs">
        <thead>
          <tr className="border-b text-muted-foreground">
            <th className="text-left py-1 font-medium">名稱</th>
            <th className="text-right py-1 font-medium">尺寸(cm)</th>
            <th className="text-right py-1 font-medium">數量</th>
            <th className="text-right py-1 font-medium">面積</th>
            <th className="text-right py-1 font-medium">材料</th>
            <th className="text-right py-1 font-medium">小計</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((p) => (
            <tr key={p.id} className="border-b border-muted/30 hover:bg-muted/20">
              <td className="py-1">
                {p.name}
                {p.isAutoGenerated && (
                  <Badge variant="outline" className="ml-1 text-[10px] px-1 py-0">自動</Badge>
                )}
              </td>
              <td className="text-right py-1 text-muted-foreground">
                {p.widthCm} × {p.heightCm}
              </td>
              <td className="text-right py-1">{p.quantity}</td>
              <td className="text-right py-1">
                <AreaDisplay area={p.totalArea} />
              </td>
              <td className="text-right py-1 text-muted-foreground max-w-[100px] truncate">
                {p.materialRef?.materialName ?? <span className="text-orange-500">未選材料</span>}
              </td>
              <td className="text-right py-1 font-medium">{formatCurrency(p.subtotal)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function CabinetResultPanel({ result }: Props) {
  const { summary } = result;

  return (
    <div className="space-y-4">
      {/* 摘要卡片 */}
      <div className="grid grid-cols-2 gap-3">
        <Card className="bg-muted/30">
          <CardContent className="p-3">
            <p className="text-xs text-muted-foreground">總板材面積</p>
            <p className="text-lg font-bold">{formatNumber(summary.totalAreaCai, 2)} 才</p>
            <p className="text-xs text-muted-foreground">{formatNumber(summary.totalAreaM2, 3)} m²</p>
          </CardContent>
        </Card>
        <Card className="bg-primary/5">
          <CardContent className="p-3">
            <p className="text-xs text-muted-foreground">本桶身合計</p>
            <p className="text-lg font-bold text-primary">{formatCurrency(summary.totalCost)}</p>
          </CardContent>
        </Card>
      </div>

      {/* 明細表 */}
      <div className="space-y-4">
        <PanelTable title="固定板件" rows={result.panels} />
        <PanelTable title="內部構件（中隔板 / 層板）" rows={result.internalParts} />

        {/* 門片 */}
        {result.doors.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold mb-2 text-muted-foreground uppercase tracking-wide">門片</h4>
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b text-muted-foreground">
                  <th className="text-left py-1 font-medium">名稱</th>
                  <th className="text-right py-1 font-medium">尺寸(cm)</th>
                  <th className="text-right py-1 font-medium">數量</th>
                  <th className="text-right py-1 font-medium">面積</th>
                  <th className="text-right py-1 font-medium">小計</th>
                </tr>
              </thead>
              <tbody>
                {result.doors.map((d) => (
                  <tr key={d.id} className="border-b border-muted/30 hover:bg-muted/20">
                    <td className="py-1">
                      {d.name}
                      <Badge variant="secondary" className="ml-1 text-[10px] px-1 py-0">
                        {d.type === "HINGED" ? "鉸鏈" : "滑門"}
                      </Badge>
                    </td>
                    <td className="text-right py-1 text-muted-foreground">{d.widthCm} × {d.heightCm}</td>
                    <td className="text-right py-1">{d.quantity}</td>
                    <td className="text-right py-1"><AreaDisplay area={d.totalArea} /></td>
                    <td className="text-right py-1 font-medium">{formatCurrency(d.subtotal)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* 五金 */}
        {result.hardware.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold mb-2 text-muted-foreground uppercase tracking-wide">五金</h4>
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b text-muted-foreground">
                  <th className="text-left py-1 font-medium">項目</th>
                  <th className="text-left py-1 font-medium">說明</th>
                  <th className="text-right py-1 font-medium">數量</th>
                  <th className="text-right py-1 font-medium">小計</th>
                </tr>
              </thead>
              <tbody>
                {result.hardware.map((h) => (
                  <tr key={h.id} className="border-b border-muted/30 hover:bg-muted/20">
                    <td className="py-1">{h.name}</td>
                    <td className="py-1 text-muted-foreground">{h.description}</td>
                    <td className="text-right py-1">{h.quantity}</td>
                    <td className="text-right py-1 font-medium">{formatCurrency(h.subtotal)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* 配件 */}
        {result.accessories.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold mb-2 text-muted-foreground uppercase tracking-wide">配件</h4>
            <table className="w-full text-xs">
              <tbody>
                {result.accessories.map((a) => (
                  <tr key={a.id} className="border-b border-muted/30 hover:bg-muted/20">
                    <td className="py-1">{a.name}</td>
                    <td className="text-right py-1 text-muted-foreground">{a.widthCm} × {a.heightCm} cm</td>
                    <td className="text-right py-1">{a.quantity}</td>
                    <td className="text-right py-1 font-medium">{formatCurrency(a.subtotal)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* 成本分解 */}
      <Separator />
      <div className="space-y-1 text-sm">
        <div className="flex justify-between text-muted-foreground">
          <span>板材</span><span>{formatCurrency(summary.panelsCost)}</span>
        </div>
        {summary.internalPartsCost > 0 && (
          <div className="flex justify-between text-muted-foreground">
            <span>內部構件</span><span>{formatCurrency(summary.internalPartsCost)}</span>
          </div>
        )}
        {summary.doorsCost > 0 && (
          <div className="flex justify-between text-muted-foreground">
            <span>門片</span><span>{formatCurrency(summary.doorsCost)}</span>
          </div>
        )}
        {summary.hardwareCost > 0 && (
          <div className="flex justify-between text-muted-foreground">
            <span>五金</span><span>{formatCurrency(summary.hardwareCost)}</span>
          </div>
        )}
        {summary.accessoriesCost > 0 && (
          <div className="flex justify-between text-muted-foreground">
            <span>配件</span><span>{formatCurrency(summary.accessoriesCost)}</span>
          </div>
        )}
        <Separator />
        <div className="flex justify-between font-bold text-base">
          <span>桶身合計</span>
          <span className="text-primary">{formatCurrency(summary.totalCost)}</span>
        </div>
      </div>
    </div>
  );
}
