// src/lib/calculations/cabinet.ts
// ✅ 純函式 — 零 UI 依賴、零副作用、完整 TypeScript 型別

import { UNIT_CONFIG } from "../config/units";
import type {
  AreaMeasure,
  CabinetUnitInput,
  CabinetUnitResult,
  CabinetUnitSummary,
  DoorResult,
  HardwareResult,
  MaterialRef,
  PanelResult,
  AccessoryResult,
  CabinetProjectResult,
} from "../../types";

// ─── 內部輔助 ─────────────────────────────────────────────────────────────────

function round(n: number, decimals: number): number {
  const factor = Math.pow(10, decimals);
  return Math.round(n * factor) / factor;
}

function toAreaMeasure(cm2: number): AreaMeasure {
  const d = UNIT_CONFIG.AREA_DECIMAL_PLACES;
  return {
    cm2: round(cm2, d),
    m2: round(cm2 / 10_000, d),
    cai: round(cm2 / UNIT_CONFIG.CAI_CM2, d),
  };
}

function calcPanelSubtotal(
  area: AreaMeasure,
  quantity: number,
  materialRef: MaterialRef | null
): number {
  if (!materialRef) return 0;
  if (materialRef.unit === "才") {
    return round(area.cai * quantity * materialRef.pricePerUnit, UNIT_CONFIG.COST_DECIMAL_PLACES);
  }
  if (materialRef.unit === "m²") {
    return round(area.m2 * quantity * materialRef.pricePerUnit, UNIT_CONFIG.COST_DECIMAL_PLACES);
  }
  return 0;
}

function buildPanelResult(params: {
  id: string;
  name: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  materialRef: MaterialRef | null;
  isAutoGenerated: boolean;
}): PanelResult {
  const { id, name, widthCm, heightCm, quantity, materialRef, isAutoGenerated } = params;
  const singleCm2 = widthCm * heightCm;
  const singleArea = toAreaMeasure(singleCm2);
  const totalArea = toAreaMeasure(singleCm2 * quantity);

  return {
    id,
    name,
    widthCm,
    heightCm,
    quantity,
    singleArea,
    totalArea,
    materialRef,
    unitCost: materialRef?.pricePerUnit ?? 0,
    subtotal: calcPanelSubtotal(singleArea, quantity, materialRef),
    isAutoGenerated,
  };
}

// ─── 固定板件生成 ─────────────────────────────────────────────────────────────

function generateFixedPanels(input: CabinetUnitInput, unitQty: number): PanelResult[] {
  const { id, widthCm, depthCm, heightCm, panelMaterialRef, backPanelMaterialRef, hasBackPanel } =
    input;

  const panels: PanelResult[] = [
    buildPanelResult({ id: `${id}-left`,   name: "左側板", widthCm: heightCm, heightCm: depthCm, quantity: unitQty, materialRef: panelMaterialRef, isAutoGenerated: true }),
    buildPanelResult({ id: `${id}-right`,  name: "右側板", widthCm: heightCm, heightCm: depthCm, quantity: unitQty, materialRef: panelMaterialRef, isAutoGenerated: true }),
    buildPanelResult({ id: `${id}-top`,    name: "頂板",   widthCm,           heightCm: depthCm, quantity: unitQty, materialRef: panelMaterialRef, isAutoGenerated: true }),
    buildPanelResult({ id: `${id}-bottom`, name: "底板",   widthCm,           heightCm: depthCm, quantity: unitQty, materialRef: panelMaterialRef, isAutoGenerated: true }),
  ];

  if (hasBackPanel) {
    panels.push(
      buildPanelResult({ id: `${id}-back`, name: "背板", widthCm, heightCm, quantity: unitQty, materialRef: backPanelMaterialRef, isAutoGenerated: true })
    );
  }

  return panels;
}

// ─── 中隔板 + 層板 ────────────────────────────────────────────────────────────

function generateInternalParts(input: CabinetUnitInput, unitQty: number): PanelResult[] {
  const parts: PanelResult[] = [];

  for (const d of input.middleDividers) {
    parts.push(buildPanelResult({
      id: d.id, name: "中隔板",
      widthCm: d.widthCm, heightCm: d.heightCm,
      quantity: d.quantity * unitQty,
      materialRef: d.materialRef, isAutoGenerated: false,
    }));
  }

  for (const s of input.shelves) {
    parts.push(buildPanelResult({
      id: s.id, name: "層板",
      widthCm: s.widthCm, heightCm: s.depthCm,
      quantity: s.quantity * unitQty,
      materialRef: s.materialRef, isAutoGenerated: false,
    }));
  }

  return parts;
}

// ─── 門片 + 五金 ──────────────────────────────────────────────────────────────

function calculateDoors(
  input: CabinetUnitInput,
  unitQty: number
): { doors: DoorResult[]; hardware: HardwareResult[] } {
  const doors: DoorResult[] = [];
  const hardware: HardwareResult[] = [];

  for (const door of input.doors) {
    const totalQty = door.quantity * unitQty;
    const singleCm2 = door.widthCm * door.heightCm;
    const singleArea = toAreaMeasure(singleCm2);
    const totalArea = toAreaMeasure(singleCm2 * totalQty);

    doors.push({
      id: door.id,
      type: door.type,
      name: door.name || (door.type === "HINGED" ? "鉸鏈門" : "滑門"),
      widthCm: door.widthCm,
      heightCm: door.heightCm,
      quantity: totalQty,
      singleArea,
      totalArea,
      materialRef: door.materialRef,
      subtotal: calcPanelSubtotal(singleArea, totalQty, door.materialRef),
    });

    if (door.type === "HINGED") {
      const hingesPerDoor = Math.max(
        UNIT_CONFIG.MIN_HINGES_PER_DOOR,
        Math.ceil(door.heightCm / UNIT_CONFIG.HINGE_SPACING_CM)
      );
      const totalHinges = hingesPerDoor * totalQty;
      const hingeRef = door.hingeMaterialRef ?? null;

      hardware.push({
        id: `${door.id}-hinge`,
        name: "鉸鏈",
        description: `門高 ${door.heightCm}cm → 每扇 ${hingesPerDoor} 個 × ${totalQty} 扇`,
        quantity: totalHinges,
        materialRef: hingeRef,
        unitCost: hingeRef?.pricePerUnit ?? 0,
        subtotal: hingeRef ? round(totalHinges * hingeRef.pricePerUnit, UNIT_CONFIG.COST_DECIMAL_PLACES) : 0,
      });
    }

    if (door.type === "SLIDING") {
      const widthChi = round(input.widthCm / UNIT_CONFIG.CM_PER_TAI_CHI, 2);
      const railRef = door.railMaterialRef ?? null;
      const railPrice = railRef?.pricePerUnit ?? 0;

      hardware.push({
        id: `${door.id}-rail-top`,
        name: "上滑軌",
        description: `桶身寬 ${input.widthCm}cm ≈ ${widthChi} 尺 × ${unitQty} 組`,
        quantity: unitQty,
        materialRef: railRef,
        unitCost: round(widthChi * railPrice, UNIT_CONFIG.COST_DECIMAL_PLACES),
        subtotal: round(widthChi * railPrice * unitQty, UNIT_CONFIG.COST_DECIMAL_PLACES),
      });

      hardware.push({
        id: `${door.id}-rail-bottom`,
        name: "下滑軌",
        description: `桶身寬 ${input.widthCm}cm ≈ ${widthChi} 尺 × ${unitQty} 組`,
        quantity: unitQty,
        materialRef: railRef,
        unitCost: round(widthChi * railPrice, UNIT_CONFIG.COST_DECIMAL_PLACES),
        subtotal: round(widthChi * railPrice * unitQty, UNIT_CONFIG.COST_DECIMAL_PLACES),
      });
    }
  }

  return { doors, hardware };
}

// ─── 踢腳板 ───────────────────────────────────────────────────────────────────

function calculateAccessories(input: CabinetUnitInput, unitQty: number): AccessoryResult[] {
  const accessories: AccessoryResult[] = [];

  if (input.kickPlate) {
    const { widthCm, heightCm, materialRef } = input.kickPlate;
    const singleArea = toAreaMeasure(widthCm * heightCm);
    const totalArea = toAreaMeasure(widthCm * heightCm * unitQty);

    accessories.push({
      id: `${input.id}-kickplate`,
      name: "踢腳板",
      widthCm, heightCm,
      quantity: unitQty,
      singleArea, totalArea,
      materialRef,
      subtotal: calcPanelSubtotal(singleArea, unitQty, materialRef),
    });
  }

  return accessories;
}

// ─── 彙總 ─────────────────────────────────────────────────────────────────────

function buildSummary(
  panels: PanelResult[],
  internalParts: PanelResult[],
  doors: DoorResult[],
  hardware: HardwareResult[],
  accessories: AccessoryResult[]
): CabinetUnitSummary {
  const allPanels = [...panels, ...internalParts];
  const totalAreaCm2 = allPanels.reduce((acc, p) => acc + p.totalArea.cm2, 0);
  const panelsCost = panels.reduce((acc, p) => acc + p.subtotal, 0);
  const internalPartsCost = internalParts.reduce((acc, p) => acc + p.subtotal, 0);
  const doorsCost = doors.reduce((acc, d) => acc + d.subtotal, 0);
  const hardwareCost = hardware.reduce((acc, h) => acc + h.subtotal, 0);
  const accessoriesCost = accessories.reduce((acc, a) => acc + a.subtotal, 0);

  return {
    totalAreaCm2: round(totalAreaCm2, 2),
    totalAreaM2: round(totalAreaCm2 / 10_000, 4),
    totalAreaCai: round(totalAreaCm2 / UNIT_CONFIG.CAI_CM2, 4),
    panelsCost,
    internalPartsCost,
    doorsCost,
    hardwareCost,
    accessoriesCost,
    totalCost: panelsCost + internalPartsCost + doorsCost + hardwareCost + accessoriesCost,
  };
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function calculateCabinetUnit(input: CabinetUnitInput): CabinetUnitResult {
  const unitQty = input.quantity;
  const panels = generateFixedPanels(input, unitQty);
  const internalParts = generateInternalParts(input, unitQty);
  const { doors, hardware } = calculateDoors(input, unitQty);
  const accessories = calculateAccessories(input, unitQty);
  const summary = buildSummary(panels, internalParts, doors, hardware, accessories);

  return { unitId: input.id, unitName: input.name, quantity: unitQty, panels, internalParts, doors, hardware, accessories, summary };
}

export function calculateCabinetProject(units: CabinetUnitInput[]): CabinetProjectResult {
  const unitResults = units.map(calculateCabinetUnit);
  return {
    unitResults,
    projectTotal: unitResults.reduce((acc, r) => acc + r.summary.totalCost, 0),
  };
}
